export enum RunStatus {
  INITIALIZED = 'INITIALIZED',
  CONFIGURED = 'CONFIGURED',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  FAILED = 'FAILED',
  TERMINATED = 'TERMINATED',
  SEALED = 'SEALED',
}
